version: "3.9"

services:
  rabbit_mq:
    build: ./rabbit-mq
    container_name: rabbit_mq
    volumes:
      - ./rabbit-mq/etc/:/etc/rabbitmq/
      - rabbit_mq_data:/var/
    ports:
      - 5672:5672
      - 15674:15672
      - 15000:15674
      - 1883:1883
      - 15675:15675
      - 61613:61613
    networks:
      backnetwork:
        ipv4_address: 10.5.0.6

  backend:
    container_name: backend
    depends_on:
      - rabbit_mq
      - db
    build: ./backend
    ports:
      - "8080:8080"
    links:
      - "rabbit_mq:mq"
    environment:
      AMQP_HOST: 10.5.0.6
      AMQP_PORT: 5672
      AMQP_USERNAME: apot
      AMQP_PASSWORD: Kurosaki8
      DB_URL: jdbc:postgresql://10.5.0.5:5432/test
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

    networks:
      backnetwork:
        ipv4_address: 10.5.0.3

  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      backnetwork:
        ipv4_address: 10.5.0.5

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 8081:80

networks:
  backnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  rabbit_mq_data:
    driver: local
  db:
    driver: local
