


spring:
  rabbitmq:
    host: my-iot-simulation-demo_rabbit_mq
    port: 5672
    username: apot
    password: Kurosaki
  datasource:
    url: jdbc:postgresql://db:5432/test
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
    hibernate:
      ddl-auto: create-drop
