
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: apot
    password: Kurosaki
  datasource:
    url: jdbc:postgresql://localhost:5433/test
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
    hibernate:
      ddl-auto: update
